### ISSUE TITLE
Check ruleset signatures

### ISSUE THREAD

**Issue by fmarier** [brave/https-everywhere-builder#21]
We should check the signature on the ruleset when we update: https://github.com/EFForg/https-everywhere/issues/18138#issuecomment-509430039.

**Comment by pipboy96** [comment]
Am I free to try to implement this?

**Comment by fmarier** [comment]
Sure, I'll be more than happy to review a PR!

**Comment by pipboy96** [comment]
@fmarier Is it fine to use `async`/`await` or should I avoid it?

**Comment by fmarier** [comment]
>  Is it fine to use `async`/`await`

That's fine by me.

If you end up rewriting existing code to use those, I'd suggest you do it in a separate commit (which doesn't otherwise change the behavior). That way it can be tested separately first, without the signature-checking additions.

**Comment by pipboy96** [comment]
@fmarier Most likely I will rewrite a significant part of code, it's indeed a good idea to separate these.

**Comment by pipboy96** [comment]
#26

**Comment by fmarier** [comment]
Fixed in #26.
